### ISSUE TITLE
Can no longer connect to password-protected channels

### ISSUE THREAD

**Issue by mekolat** [reactiflux/discord-irc#332]
Prior to updating to `2.5.0` (was on `2.4.2`) my setup worked just fine, however now discord-irc refuses to connect to password-protected channels and I haven't changed anything in the settings.
The affected channel is `#hchat` on Rizon, I haven't tried other password-protected channels. The regular channels work just fine.

I get a `Illegal channel name` error message when debug is enabled:
```yaml
ERROR: Unhandled message: { prefix: 'magnet.rizon.net',
  server: 'magnet.rizon.net',
  command: '479',
  rawCommand: '479',
  commandType: 'normal',
  args:
   [ 'HercDiscord',
     '#hchat',
     '<password removed>',
     'Illegal channel name' ] }
```
<br>
<details><summary>full config file (click here)</summary>

```json
[
	{
		"nickname": "HercDiscord",
		"server": "irc.rizon.net",
		"discordToken": "<removed token>",
		"channelMapping": {
			"306632465294819331": "#Hercules",
			"306633733472256011": "##Hercules-script",
			"306634170858471425": "##Hercules-dev",
			"306634060438962207": "#Hercules-Testers",
			"306633825750876162": "#hchat <removed password>"
		},
		"ircOptions": {
			"userName": "HercDiscord",
			"realName": "Hercules Discord bridge",
			"password": "<removed password>",
			"port": 6697,
			"secure": true,
			"autoRejoin": true,
			"autoRenick": true
		},
		"format": {
			"commandPrelude": "Command sent by {$nickname}",
			"ircText": "<{$displayUsername}> {$text}",
			"urlAttachment": "<{$displayUsername}> {$attachmentURL}",
			"discord": "**<{$author}>** {$withMentions}"
		},
		"ignoreUsers": {
			"irc": [
				"Hercules"
			],
			"discord": []
		},
		"ircNickColor": false,
		"ircStatusNotices": false
	}
]
```

</details>
